### ISSUE TITLE
你好，在军旗博弈平台上我使用军旗那部分代码的exe文件与平台提供的exe文件对战时，在第十步出现了行棋错误，请问您有遇到这个问题没，或者有什么解决办法。

### ISSUE THREAD

**Issue by MJ-NCEPU** [YuelinWang/computer_game#1]

**Comment by shuangxunian** [comment]
sry，没有遇到过哦，而且开源出来的对战代码已经是四年前的了，不建议直接用；最好弄明白逻辑后再取其精华自己开发~

**Comment by MJ-NCEPU** [comment]
好的，感谢回复，我先去看一下你们的视频。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年4月17日(周一) 上午10:18
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [shuangxunian/computer_game] 你好，在军旗博弈平台上我使用军旗那部分代码的exe文件与平台提供的exe文件对战时，在第十步出现了行棋错误，请问您有遇到这个问题没，或者有什么解决办法。 (Issue #1)




 
sry，没有遇到过哦，而且开源出来的对战代码已经是四年前的了，不建议直接用；最好弄明白逻辑后再取其精华自己开发~
